### ISSUE TITLE
deamon.spotter cronstyle with plesk

### ISSUE THREAD

**Issue by MrDalle** [Ysurac/FlightAirMap#304]
Hey!

i moved the map to a new vserver which is running a plesk.
in order to make the deamon.spotter working i have to insert smth. like "0 22 * * 1-5"

Can you provide a cron style for me?

Thanks!

**Comment by Ysurac** [comment]
**$globalDaemon** must be set to **FALSE** in *require/settings.php*.
For cron you can use something like:

    0 * * * * root /usr/bin/php /var/www/FlightAirMap/scripts/spotter-daemon.php >/dev/null 2>&1

This will run the script every hours.
Every 2 hours can also be enough:

    0 */2 * * * root /usr/bin/php /var/www/FlightAirMap/scripts/spotter-daemon.php >/dev/null 2>&1

**Comment by MrDalle** [comment]
<img width="1081" alt="bildschirmfoto 2017-06-01 um 17 17 37" src="https://cloud.githubusercontent.com/assets/7756672/26686770/489f1f08-46ee-11e7-9ed8-f3a710bf7e60.png">

i guess i just have to insert "0 * * * *" or?

**Comment by MrDalle** [comment]
if i run the script like i did with my other plesk server i get this error message... 

<img width="581" alt="bildschirmfoto 2017-06-01 um 17 28 21" src="https://cloud.githubusercontent.com/assets/7756672/26687373/d37993e6-46ef-11e7-8756-83136892bc63.png">

**Comment by Ysurac** [comment]
Yes but also check the *Do not notify* box, you don't have to get all log info.
Sorry, In fact I was giving info for **update-db.php**, that should be run every hour:

    0 * * * * root /usr/bin/php /var/www/FlightAirMap/scripts/update-db.php >/dev/null 2>&1

But **daemon-spotter.php**, should be run more often, at least less than your **$globalLiveInterval**:

       */2 * * * * root /usr/bin/php /var/www/FlightAirMap/scripts/spotter-daemon.php >/dev/null 2>&1

This will run it every  2 minutes for example.

The ATC error is because you use a VA source, but **$globalVATSIM** or **$globalIVAO** is not set to **TRUE**, I fixed that in latest commit.
